### ISSUE TITLE
Error when calculating PLECs

### ISSUE THREAD

**Issue by ValeryPolyakov** [oddt/oddt#101]
For a large number of PDB codes in v2018 edition of PDB bind, an attempt to calculate PLEC fingerprint results in an error message. Here is how to reproduce it. A similar error happens when using sdf instead of a mol2 reader. 

pdbid = "1a37"

baseDir = os.getcwd() + "/v2018/"
prot_pattern = baseDir + '%s/%s_pocket.pdb' 
ligand_pattern = baseDir + '%s/%s_ligand.mol2'

protein = next(oddt.toolkit.readfile('pdb', prot_pattern %(pdbid, pdbid)))
ligand = next(oddt.toolkit.readfile('mol2', ligand_pattern %(pdbid, pdbid)))
PLEC = oddt.fingerprints.PLEC(ligand, protein, size=4092, depth_protein=5, depth_ligand=1, distance_cutoff=4.5,sparse=True)
print(PLEC)

Below is the error message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-232f8c1d95b4> in <module>
      8 protein.protein = True
      9 ligand = next(oddt.toolkit.readfile('mol2', ligand_pattern %(pdbid, pdbid)))
---> 10 PLEC = oddt.fingerprints.PLEC(ligand, protein, size=4092, depth_protein=5, depth_ligand=1, distance_cutoff=4.5,sparse=True)
     11 print(PLEC)

~\AppData\Local\Continuum\anaconda3\envs\my-rdkit-env\lib\site-packages\oddt\fingerprints.py in PLEC(ligand, protein, depth_ligand, depth_protein, distance_cutoff, size, count_bits, sparse, ignore_hoh)
    734         protein_mask = protein_mask & (protein.atom_dict['resname'] != 'HOH')
    735     protein_dict = protein.atom_dict[protein_mask]
--> 736     ligand_dict = ligand.atom_dict[ligand.atom_dict['atomicnum'] != 1]
    737 
    738     # atoms in contact

~\AppData\Local\Continuum\anaconda3\envs\my-rdkit-env\lib\site-packages\oddt\toolkits\rdk.py in atom_dict(self)
    555         # check cache and generate dicts
    556         if self._atom_dict is None:
--> 557             self._dicts()
    558         return self._atom_dict
    559 

~\AppData\Local\Continuum\anaconda3\envs\my-rdkit-env\lib\site-packages\oddt\toolkits\rdk.py in _dicts(self)
    664                       ]
    665 
--> 666         atom_dict = np.empty(self.Mol.GetNumAtoms(), dtype=atom_dtype)
    667         metals = [3, 4, 11, 12, 13, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
    668                   30, 31, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,

AttributeError: 'NoneType' object has no attribute 'GetNumAtoms'

**Comment by mwojcikowski** [comment]
Remember that RDKit is picky about the molecules that it parses, so you need to check if the produced molecule is not empty, as it is in this case. 

```python
ligand = next(oddt.toolkit.readfile('mol2', ligand_pattern %(pdbid, pdbid)))
if ligand.Mol:
    PLEC = oddt.fingerprints.PLEC(ligand, protein, size=4092, depth_protein=5, depth_ligand=1, distance_cutoff=4.5,sparse=True)
```
I think that `if ligand:` should be enough too, but I sometimes had problems with propagating the `None` as an output of `Molecule()` init, so using `ligand.Mol` is safer.

**Comment by ValeryPolyakov** [comment]
Thanks Maciej. It works now, but I had to check both ligand and protein:

if ligand.Mol and protein.Mol

**Comment by ValeryPolyakov** [comment]
Ok.
