### ISSUE TITLE
shape of RDKit 3D molecule

### ISSUE THREAD

**Issue by ValeryPolyakov** [oddt/oddt#102]
I am trying to calculate a shape FP for RDkit molecule, but getting an error message:

mol1 = Chem.MolFromSmiles('COc1ccc2c(c1)[nH]c(n2)[S@@](=O)Cc1ncc(c(c1C)OC)C')
mol1 = Chem.AddHs(mol1)
mol1 = Chem.EmbedMolecule(mol1)

shape1 = oddt.shape.electroshape(mol1)

Is it possible to do this?

Thanks.

**Comment by mwojcikowski** [comment]
It is possible to use RDKit molecules, although you have to use ODDT Molecule  object within ODDT.

```python
import oddt
oddt.toolkit = oddt.toolkits.rdk
...
shape1 = oddt.shape.electroshape(oddt.toolkit.Molecule(mol1))
```

On the other note, the SMILES in your example is not valid. How did you get it?

**Comment by ValeryPolyakov** [comment]
Hi Maciej, 

Sorry about the confusion with the SMILES. I probably picked it from a wrong place without checking.

Nevertheless, your code did not work for my, but I found a workaround:

import os
import oddt
import oddt.shape
from rdkit import rdBase
from rdkit.Chem import AllChem as Chem, rdMolAlign

#read a 2D molecule using RDkit
mol1 = Chem.MolFromSmiles('COc1ccc2c(c1)[nH]c(n2)[S@@](=O)Cc1ncc(c(c1C)OC)C')

#add atoms, if needed
mol1 = Chem.AddHs(mol1)

#generate a 3D structure (it will modify existing molecule)
Chem.EmbedMolecule(mol1)

#Make CTAB block as a string to convert to ODDT format
mol1 = Chem.MolToMolBlock(mol1)

#read the string into ODDT molecule
mol1 = oddt.toolkit.readstring('sdf', mol1)

#Calculate electoshape. Shows that the two conformers have very different shape
shape1 = oddt.shape.electroshape(mol1)
