### ISSUE TITLE
Append mode for oddt.toolkits.rdk.Outputfile(format, filename, overwrite=False)

### ISSUE THREAD

**Issue by ValeryPolyakov** [oddt/oddt#105]
The output file only has overwrite = True or False. It is possible to add an append mode to write multiple molecules to the same SD file? Or maybe there is another way to do it?

**Comment by ValeryPolyakov** [comment]
Also, can I convert an ODDT 3D molecule into an RDkit molecule? Thanks.

**Comment by mwojcikowski** [comment]
There is unfortunately no way of appending already closed `Outputfile`.

You can access  RDKit `Mol` object directly. It is located as Molecule parameter: `Molecule.Mol`.

**Comment by ValeryPolyakov** [comment]
Hi Maciej,

I do not think it works:

import os
import oddt
import oddt.shape
from rdkit import rdBase
from rdkit.Chem import AllChem as Chem, rdMolAlign

#read a 2D molecule using RDkit
mol1 = Chem.MolFromSmiles('COc1ccc2c(c1)[nH]c(n2)[S@
@](=O)Cc1ncc(c(c1C)OC)C')

#add atoms, if needed
mol1 = Chem.AddHs(mol1)

#generate a 3D structure (it will modify existing molecule)
Chem.EmbedMolecule(mol1)

#Make CTAB block as a string to convert to ODDT format
mol1 = Chem.MolToMolBlock(mol1)

#read the string into ODDT molecule
mol1 = oddt.toolkit.readstring('sdf', mol1)

print(Chem.MolToMolBlock(mol1.mol))

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call
last)<ipython-input-45-5d950dd1a53b> in <module>     21 mol1 =
oddt.toolkit.readstring('sdf', mol1)     22 ---> 23
print(Chem.MolToMolBlock(mol1.mol))     24      25 #get the lowest
conformer
AttributeError: 'Molecule' object has no attribute 'mol'

**Comment by mwojcikowski** [comment]
Just use `mol1.Mol` as RDKit mol

```python
rdkit_mol = mol1.Mol
for atom in rdkit_mol.GetAtoms():
    print(atom.GetSymbol())
```

**Comment by ValeryPolyakov** [comment]
Thanks, that works for me!
