### ISSUE TITLE
Cannot recognize resid and resname of pdb file

### ISSUE THREAD

**Issue by tongjh994** [oddt/oddt#110]
Hi, first of all, thanks you for the development of this wonderful module. Here is my problem:
I read a pdb file in this way:

> prot = next(oddt.toolkits.ob.readfile("pdb","4eiy.pdb"))

And when I check atom dict through:
> prot.atom_dict

the resnums of all atoms are 0 and the resnames of them are " ". Is there something wrong? The version of each module is here:
pybel 2.4.1
rdkit 2017.03.3
oddt 0.6(I've installed the 0.6 version from release, but the value of oddt.get_version() is still 0.5)

**Comment by mwojcikowski** [comment]
Try setting `prot.protein = True` after you read in the molecule. This flag changes the residue detection routines for ligands and proteins.

**Comment by tongjh994** [comment]
Thanks a lot, it works!
