### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by hadim** [oddt/oddt#112]
I know you already have a conda channel but it's a good practice to rely on a minimum number of channels when using conda.

I like to have all my deps in `conda-forge` whenever possible so I made a `conda-forge` package for oddt: https://github.com/conda-forge/staged-recipes/pull/11074

Happy to give you control on the recipe if you guys want.

**Comment by mwojcikowski** [comment]
@hadim Thanks for that contribution, it's highly appreciated! Sure, I can review/update that package too. Let me know what you need.

From a first glance it is a bit on a heavy side - requires both OpenBabel and RDKit, but it might be good to have a full experience out of the box.

**Comment by hadim** [comment]
I put both in the package but if you think it's too much let me know. You obviously have stronger expertise than me to choose which one is best.

That being said having both is not heavy IMO.

**Comment by mwojcikowski** [comment]
It's fine to have OB and RDKit.

**Comment by hadim** [comment]
The package has been merged and should be available soon on conda-forge.

Happy to fix the toolkit thing or give you control over the repo if needed.

**Comment by mwojcikowski** [comment]
Great! Thanks again for the contribution!
