### ISSUE TITLE
Field name issue

### ISSUE THREAD

**Issue by XiaochangLiu-UoE** [oddt/oddt#116]
Hi,

Thanks for your efforts in developing this great kit. 

I was using the `interaction.hbonds()` to detect hydrogen bonds between a small molecule and a protein, but when I tried to print the contacting residues' numbers, I got a warning about no field of name `resnumber`, which should be one of the fields of the residue `atom_dict` according to the official document. So I checked your src and found that under the `Molecule` class in toolkits/rdk.py and ob.py, the field name is defined as `resnum` when defining the `atom_dict`.  Maybe the document needs a slight change.

**Comment by mwojcikowski** [comment]
Thanks for spotting the problem, I will patch the docs.

**Comment by mwojcikowski** [comment]
Docs patched
