### ISSUE TITLE
Protein-ligand PDB

### ISSUE THREAD

**Issue by haroldgrosjean** [oddt/oddt#117]
Hello,

I would like to use your (great!) tool to study protein-ligand interactions. Both are contained in the same PDB which is an output from a MD trajectory. When I load my complex with ``rdk.Chem.MolFromPDBFile`` and inputs it into ``ExtractPocketAndLigand``  the following error returns: ``ValueError: No ligands``.  I suspect it because the ligand field do not contain the HEATM flag preventing recognition. After this step, I would like to analyze the interactions with ``hbond_acceptor_donor``.

Could you, please, indicate to me the best way to overcome such a problem.

Many thanks,

Harold

**Comment by haroldgrosjean** [comment]
Hi,

I would like to amend my previous question. I found the ``oddt.toolkits.extras.rdkit.fixer.ExtractPocketAndLigand`` which seems to be what I was looking for. However, when I try to use it returns me ``AttributeError: module 'oddt.toolkits.extras.rdkit' has no attribute 'fixer'``.

Any idea about how to debug?

Cheers,

Harold

**Comment by mwojcikowski** [comment]
Could you please provide a sample of code that generates the error? Also
which exact version of ODDT are you using?

----
Pozdrawiam,  |  Best regards,
Maciek Wójcikowski
maciek@wojcikowski.pl


czw., 23 kwi 2020 o 16:57 haroldgrosjean <notifications@github.com>
napisał(a):

**Comment by mwojcikowski** [comment]
@haroldgrosjean closing this issue due to lack of information
