### ISSUE TITLE
PLEC fingerprint: how to trace bits back to parent substructures

### ISSUE THREAD

**Issue by luponzo86** [oddt/oddt#118]
Hello,
thanks for putting together this awesome package!

I recently starting working with your implementation of PLEC fingerprint and I was wondering if there is a way to associate each returned bit to the substructure that generated it.
In the manuscript (Wojcikowski 2019), this sentence seems to suggest that it is indeed possible:

> Importantly, each bit can be traced to a parent substructure, which expands the many possible applications of the PLEC FP.

Is there already a function to obtain such information? Is it in the works? If not, do you have any suggestions about how that results could be obtained by hacking the code a little?

Thank you so much!
Luca

**Comment by mwojcikowski** [comment]
Hi @luponzo86,

Unfortunately there is no specific function to extract structural information about the bit pairs. That said, it is totally possible, as we mentioned in the paper quoted by you. We can craft a function that would get such information if you provide more information on what you would like to get from it. List of indices, image? 

If you wish to play around by yourself you need to catch which atom was used as a root atom and environment depth to generate each bit. Similarly to how RDKit does it for Morgan fingerprints.

Best,
Maciek

**Comment by luponzo86** [comment]
Hi @mwojcikowski 
thank you for your reply!

I would really appreciate if you could help me with creating such function!
Since I'd like to use this information to identify important substructures in a molecule and possibly further analyze them with RDKit/openbabel, it would be great to have a sort of dictionary that maps bits to parent substructures (or viceversa), with the latter provided in whatever format is better for later being manipulated in RDKit or openbabel, and with indexes that indicate their position on the original molecule. I only recently started working with RDKit and openbabel, but I guess that, given a list of indices as you suggest, then it should be possible to extract the relative substructure from the original molecule. Side note: would this require a "flag" to be turned on when generating the fingerprint? Something like:
`oddt.fingerprints.PLEC(lig_mol, protein=prot_mol, map_bits=True)`

Please let me know if this makes sense... 
I would be extremely grateful for any help you could give me,
and thanks for taking the time answering this request!

Luca
