### ISSUE TITLE
examples?

### ISSUE THREAD

**Issue by hainm** [oddt/oddt#12]
hi, nice project.

can you add some examples in github? having jupyter notebook is great too. thanks.

**Comment by mwojcikowski** [comment]
Is there anything specific you'd like to see?

**Comment by hainm** [comment]
No, there is not. I just want to try to use `oddt` to understand its workflow. Looking at example is easiest to learn.

**Comment by mwojcikowski** [comment]
They are here: https://github.com/oddt/jcheminf
I'll put some links to them in README.

**Comment by hainm** [comment]
thanks.
