### ISSUE TITLE
Error reading rdkit's ROMol object for PLEC

### ISSUE THREAD

**Issue by dagarshali** [oddt/oddt#120]
I was using this package (which my the way is awesome). I was working with rdkit mol objects and the following piece of code gave the error. 

Looks like atom_dict is not one of the descriptors in RDkit. I think it is atomDict. Any help to fix this would help me and bunch of other facing the same problem.

protein = next(oddt.toolkit.readfile('pdb', 'covid.pdb'))
mol = df['ROMol'][0]
fp = PLEC(mol,protein)

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-18-13a12cc3d068> in <module>
>       1 protein = next(oddt.toolkit.readfile('pdb', 'covid.pdb'))
>       2 mol = df['ROMol'][0]
> ----> 3 fp = PLEC(mol,protein)
> 
> ~/opt/anaconda3/envs/myoddt/lib/python3.7/site-packages/oddt/fingerprints.py in PLEC(ligand, protein, depth_ligand, depth_protein, distance_cutoff, size, count_bits, sparse, ignore_hoh)
>     752         protein_mask = protein_mask & (protein.atom_dict['resname'] != 'HOH')
>     753     protein_dict = protein.atom_dict[protein_mask]
> --> 754     ligand_dict = ligand.atom_dict[ligand.atom_dict['atomicnum'] != 1]
>     755 
>     756     # atoms in contact
> 
> AttributeError: 'Mol' object has no attribute 'atom_dict'

**Comment by mwojcikowski** [comment]
You need to use `oddt.toolkit.Molecule` objects for most of functionality within ODDT. While some functions might run on `pybel.Molecule` objects, most will not. Same goes for RDKit `Chem.Mol`. To create ODDT molecule from RDKit object use following code:

```python
import oddt
# You want to use RDKit as your toolkit
oddt.tookit = oddt.toolkits.rdk
...
rdkit_mol = Chem.MolFromSmiles('CC')
oddt_mol = oddt.toolkit.Molecule(rdkit_mol)
```
In pandas you can convert entire column with `apply`
```python
df['oddt_molecule'] = df['ROMol'].apply(oddt.toolkit.Molecule)
```

**Comment by dagarshali** [comment]
Hi,
Thanks for getting back to me. I was first using the same process that you are suggesting and still got the same error. To repeat the exercise, I took on protein pdb and ligand pdb file and read directly using 

1. I tried below and it worked just fine

> protein = next(oddt.toolkit.readfile('pdb', 'protein.pdb'))
> ligand = next(oddt.toolkit.readfile('pdb', 'ligand.pdb'))
> fp = PLEC(ligand,protein)
> 

2. I then tried to read the same pdb for protein and ligand using RDKit and got the error as below. I have attached the protein and ligand pdb files for you to replicated the error
[Archive.zip](https://github.com/oddt/oddt/files/4669610/Archive.zip)
[Archive.zip](https://github.com/oddt/oddt/files/4669613/Archive.zip)



> protein = oddt.toolkit.Molecule(Chem.MolFromPDBFile,'protein.pdb')
> ligand = oddt.toolkit.Molecule(Chem.MolFromPDBFile,'ligand.pdb')
> fp = PLEC(ligand,protein)

Error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-493ceae2b70e> in <module>
----> 1 fp = PLEC(ligand,protein)

~/opt/anaconda3/envs/myoddt/lib/python3.7/site-packages/oddt/fingerprints.py in PLEC(ligand, protein, depth_ligand, depth_protein, distance_cutoff, size, count_bits, sparse, ignore_hoh)
    747     result = []
    748     # removing h
--> 749     protein_mask = protein_no_h = (protein.atom_dict['atomicnum'] != 1)
    750     if ignore_hoh:
    751         # a copy is needed, so not modifing inplace

~/opt/anaconda3/envs/myoddt/lib/python3.7/site-packages/oddt/toolkits/ob.py in __getattr__(self, attr)
    300             if attr.lower() == desc.lower():
    301                 return self.calcdesc([desc])[desc]
--> 302         raise AttributeError('Molecule has no such property: %s' % attr)
    303 
    304     def _clear_cache(self):

AttributeError: Molecule has no such property: atom_dict
