### ISSUE TITLE
Incompatible electroshape FPs going from 0.5 to 0.7

### ISSUE THREAD

**Issue by ValeryPolyakov** [oddt/oddt#122]
[test.txt](https://github.com/oddt/oddt/files/4696800/test.txt)
I am calculating electroshape FPs for the attached molecule (3D sdf). Calculated FPs seems to change from version 0.5 to 0.7 of your software. Here is the code sample:

            oddt_conf = oddt.toolkit.readstring('sdf', str_conf)
            print(oddt.__version__)
            q_fp_float = electroshape(oddt_conf)
            print('q_fp_float =', q_fp_float)

For 0.7:
q_fp_float = [ 6.05517244  2.65961981  2.37084842 12.48709202  4.8921752  -2.21949124
 12.46013355  4.75548124 -3.2248311  13.39133572  4.07966982  2.44799709
 12.86302353  4.20777922  3.77391025]

For 0.5
q_fp_float = [ 3.61656475  1.58240819 -0.61808103  6.85135412  3.43336844 -2.68338418
  5.76101255  3.1258297   2.13901448  5.00821384  1.13478267  0.84174761
  5.00821384  1.13478267  0.84174761]

Is there a way to maintain compatibility?

Thanks,

Valery

**Comment by mwojcikowski** [comment]
Hi Valery,

Electroshape code was not changed for a very long time. I will try to reproduce your problem, but since you already have both environments if they use the same versions of OpenBabel or RDKit (whichever you use)?

**Comment by mwojcikowski** [comment]
I think I identified your problem: you do not generate charges and SDF does not contain partial charges. In 0.7 your charges are all 0. In 0.5 when `Molecule.partialcharge` method was called and RDKit had no charges, a Gasteiger charge was generated. That worked automatically, but could generate unintentional computations.
The solution is quite easy, add `oddt_conf.calccharges()` to your script. The Gesteiger charges ar the default.

My script looks as follows:
```python
import oddt
from oddt.shape import electroshape

oddt.toolkit = oddt.toolkits.rdk

oddt_conf = next(oddt.toolkit.readfile('sdf', 'Pobrane/test.txt'))
oddt_conf.calccharges()
print(oddt.__version__)
q_fp_float = electroshape(oddt_conf)
print('q_fp_float =', q_fp_float)
```
The output using current master and RDKit  2020.03.1:
```python
q_fp_float = [ 5.93498898  2.64973307  2.49396825 12.71878529  4.71270752 -3.55573297
 12.36122704  4.83488512  1.09274936 13.69936244  3.97606269  2.07045312
 12.81167018  4.09163937  3.87077527]
```
Without calccharges:
```python
q_fp_float = [ 3.61656475  1.58240819 -0.61808103  6.85135412  3.43336844 -2.68338418
  5.76101255  3.1258297   2.13901448  5.00821384  1.13478267  0.84174761
  5.00821384  1.13478267  0.84174761]
```

**Comment by ValeryPolyakov** [comment]
Thanks Maciej. I worry about the backward compatibility. I have done a large number of calculations with v0.5. Should I just not upgrade?

**Comment by mwojcikowski** [comment]
@ValeryPolyakov I strongly believe that you should upgrade, but first make sure that you know your RDKit version that you used originally, and the new code with `calccharges` method works as expected.

I can help you checking that if you provide exact version of RDKit that you used.

**Comment by ValeryPolyakov** [comment]
Hi Maceij, what is oddt.toolkit = oddt.toolkits.rdk? Is this for backwards compatibility? I tested 4 conditions with the following script:
import oddt
from oddt.shape import electroshape
import rdkit
from rdkit.Chem import AllChem as Chem
print("RDkit version: ", rdkit.__version__)
print("ODDT version: ", oddt.__version__)

for i in range(4):
	if i % 2 == 1:
		makeCharges = False
	else:
		makeCharges = True

	if i < 2:
		useRDkit = False
	else:
		useRDkit = True

	if useRDkit == False:
		print("Using ODDT to read file")
		oddt_conf = next(oddt.toolkits.rdk.readfile('sdf', 'ShapeDB/test.txt'))
	else:
		print("Using RDkit to read file")
		suppl = Chem.SDMolSupplier('ShapeDB/test.txt')
		str_conf = Chem.MolToMolBlock(suppl[0])
		oddt_conf = oddt.toolkit.readstring('sdf', str_conf)

	if makeCharges == False:
		print("Charges are NOT added")
	else:
		oddt_conf.calccharges()
		print("Charges are added")
		
	q_fp_float = electroshape(oddt_conf)
	print('q_fp_float =', q_fp_float)

On newer system:
RDkit version:  2020.03.1
ODDT version:  0.7
Using ODDT to read file
Charges are added
q_fp_float = [ 5.93498898  2.64973307  2.49396825 12.71878529  4.71270752 -3.55573297
 12.36122704  4.83488512  1.09274936 13.69936244  3.97606269  2.07045312
 12.81167018  4.09163937  3.87077527]
Using ODDT to read file
Charges are NOT added
q_fp_float = [ 3.61656475  1.58240819 -0.61808103  6.85135412  3.43336844 -2.68338418
  5.76101255  3.1258297   2.13901448  5.00821384  1.13478267  0.84174761
  5.00821384  1.13478267  0.84174761]
Using RDkit to read file
Charges are added
q_fp_float = [ 6.05517244  2.65961981  2.37084842 12.48709202  4.8921752  -2.21949124
 12.46013355  4.75548124 -3.2248311  13.39133572  4.07966982  2.44799709
 12.86302353  4.20777922  3.77391025]
Using RDkit to read file
Charges are NOT added
q_fp_float = [ 6.05517244  2.65961981  2.37084842 12.48709202  4.8921752  -2.21949124
 12.46013355  4.75548124 -3.2248311  13.39133572  4.07966982  2.44799709
 12.86302353  4.20777922  3.77391025]

on older:

RDkit version:  2019.09.1
ODDT version:  0.5
Using ODDT to read file
Charges are added
q_fp_float = [ 5.93498898  2.64973307  2.49396825 12.71878529  4.71270752 -3.55573297
 12.36122704  4.83488512  1.09274936 13.69936221  3.97606276  2.07045307
 12.81166993  4.09163944  3.87077531]
Using ODDT to read file
Charges are NOT added
q_fp_float = [ 3.61656475  1.58240819 -0.61808103  6.85135412  3.43336844 -2.68338418
  5.76101255  3.1258297   2.13901448  5.00821384  1.13478267  0.84174761
  5.00821384  1.13478267  0.84174761]
Using RDkit to read file
Charges are added
q_fp_float = [ 5.93498898  2.64973307  2.49396825 12.71878529  4.71270752 -3.55573297
 12.36122704  4.83488512  1.09274936 13.69936221  3.97606276  2.07045307
 12.81166993  4.09163944  3.87077531]
Using RDkit to read file
Charges are NOT added
q_fp_float = [ 3.61656475  1.58240819 -0.61808103  6.85135412  3.43336844 -2.68338418
  5.76101255  3.1258297   2.13901448  5.00821384  1.13478267  0.84174761
  5.00821384  1.13478267  0.84174761]

So, it looks like reading with RDkit does not require setting charges with new ODDT, It it correct?

Thanks,

Valery

**Comment by mwojcikowski** [comment]
ODDT supports both OpenBabel and RDKit, and OB takes precedence if both are available. Using `oddt.toolkit = oddt.toolkits.rdk` you force to use RDKit, similarly `oddt.toolkit = oddt.toolkits.ob` will use OpenBabel.

To check which one you are actually using you may check your `oddt.toolkit.backend` variable. The code you provided suggests that you use mix of RDKit and Openbabel. Openbabel does not require to generate the charges also has slightly different partial charges than RDKit.

I strongly advice not to mix the two toolkits together, as things might get weird sometimes, especially atom typing and aromaticity can get messed up.

In your case you get more variations: RDKit removes Hs when reading molfile/SDF.
To get the results I think you want you can use OB toolkit but you need to remove Hs befere generating the electroshape vector:
```python
oddt_conf = next(oddt.toolkit.readfile('sdf', 'test.txt'))
oddt_conf.removeh()
q_fp_float = electroshape(mol)
print('q_fp_float =', q_fp_float)
```
```python
q_fp_float = [ 6.05517244  2.65961981  2.37084842 12.48709202  4.8921752  -2.21949124
 12.46013355  4.75548124 -3.2248311  13.39133572  4.07966982  2.44799709
 12.86302353  4.20777922  3.77391025]
```

**Comment by mwojcikowski** [comment]
To avoid confusion I will add add few lines to check if all partial charges are non-zero

**Comment by ValeryPolyakov** [comment]
Hi Maceij, 
So Hs could be removed for backwards compatibility? Would not it result is distorted fingerprints?
Thanks, Valery

**Comment by ValeryPolyakov** [comment]
Thanks. In my case, it would be hard to trace back, because I upgraded some computers, but did not upgrade others. Can you suggest a forward looking procedure for reading of a CTAB conformer (string) and generating electroshapes, so that it would not change with future upgrades? I would prefer not to use OB, if possible, since this is an additional dependency. Do I need to generate explicit charges or not?

**Comment by ValeryPolyakov** [comment]
Hi Maceij, I also just realized that the discrepancy only happens on windows computers. For Linux, the output is the same:
RDkit version:  2020.03.1
ODDT version:  0.7
Using ODDT to read file
Charges are added
q_fp_float = [ 5.93498898  2.64973307  2.49396825 12.71878529  4.71270752 -3.55573297
12.36122704  4.83488512  1.09274936 13.69936221  3.97606276  2.07045307
12.81166993  4.09163944  3.87077531]
Using ODDT to read file
Charges are NOT added
q_fp_float = [ 3.61656475  1.58240819 -0.61808103  6.85135412  3.43336844 -2.68338418
  5.76101255  3.1258297   2.13901448  5.00821384  1.13478267  0.84174761
  5.00821384  1.13478267  0.84174761]
Using RDkit to read file
Charges are added
q_fp_float = [ 5.93498898  2.64973307  2.49396825 12.71878529  4.71270752 -3.55573297
12.36122704  4.83488512  1.09274936 13.69936221  3.97606276  2.07045307
12.81166993  4.09163944  3.87077531]
Using RDkit to read file
Charges are NOT added
q_fp_float = [ 3.61656475  1.58240819 -0.61808103  6.85135412  3.43336844 -2.68338418
  5.76101255  3.1258297   2.13901448  5.00821384  1.13478267  0.84174761
  5.00821384  1.13478267  0.84174761]

And:

RDkit version:  2019.03.3
ODDT version:  0.5
Using ODDT to read file
Charges are added
q_fp_float = [ 5.93498898  2.64973307  2.49396825 12.71878529  4.71270752 -3.55573297
12.36122704  4.83488512  1.09274936 13.69936221  3.97606276  2.07045307
12.81166993  4.09163944  3.87077531]
Using ODDT to read file
Charges are NOT added
q_fp_float = [ 3.61656475  1.58240819 -0.61808103  6.85135412  3.43336844 -2.68338418
  5.76101255  3.1258297   2.13901448  5.00821384  1.13478267  0.84174761
  5.00821384  1.13478267  0.84174761]
Using RDkit to read file
Charges are added
q_fp_float = [ 5.93498898  2.64973307  2.49396825 12.71878529  4.71270752 -3.55573297
12.36122704  4.83488512  1.09274936 13.69936221  3.97606276  2.07045307
12.81166993  4.09163944  3.87077531]
Using RDkit to read file
Charges are NOT added
q_fp_float = [ 3.61656475  1.58240819 -0.61808103  6.85135412  3.43336844 -2.68338418
  5.76101255  3.1258297   2.13901448  5.00821384  1.13478267  0.84174761
  5.00821384  1.13478267  0.84174761]

**Comment by marketkiller** [comment]
That's interesting, actually. I also did an upgrade from version 0.5 to 0.7, but I didn't notice any difference in fingerprints for the above example neither between versions nor between Windows vs Linux. Could it be because I didn't have OpenBabel installed on neither machine and thus oddt.toolkit defaulted to "rdk"? (which presumably doesn't affect electroshape calcs the way OB does?)

**Comment by mwojcikowski** [comment]
I think I was wrong with initial assessment. The issue is most probably caused by the mix of OB and RDKit using windows binaries, where some plugins might not be available for OB.

You should be safe with using RDKit only.

@ValeryPolyakov choosing an exact charge model might avoid falling back to some other model if the other is not available, which might happen for OB, as you witnessed. I would not expect electroshape to change in the nearest future. Also using gasteiger charges as default is probably the best for general use.

If any significant changes would be introduced, I will list them explicitly in the changelog.

**Comment by ValeryPolyakov** [comment]
Thanks a lot!
