### ISSUE TITLE
error_Loky-backed parallel loops

### ISSUE THREAD

**Issue by parkc23** [oddt/oddt#132]
Hi,
Thank you for your efforts on ODDT. I ran into a problem as shown below while trying to run oddt_cli. Could you take a look?
 
~/anaconda2/lib/python2.7/site-packages/sklearn/ensemble/base.py:154: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
n_jobs = min(effective_n_jobs(n_jobs), n_estimators)

Thanks a lot.

**Comment by mwojcikowski** [comment]
Hi,

This is just an information log from joblib. Does it trigger an error? By itself it is harmless.

**Comment by parkc23** [comment]
Thanks for the quick attention. I just thought that this error might have caused the docked geometry getting messed up, but I guess it's a separate issue.

**Comment by mwojcikowski** [comment]
This is unrelated. Please provide the ligand in question in the other thread. I'm closing this one, feel free to reopen if there is different issue.
