### ISSUE TITLE
Problem reproducing PLEC fingerprint on pickled molecule

### ISSUE THREAD

**Issue by luponzo86** [oddt/oddt#140]
I noticed that pickling a molecule imported, for instance, from a `mol2` file, changes the result of computing the PLEC fingerprint.

In pseudocode:
```
import pickle
from oddt.toolkits.ob import readfile
from oddt.fingerprints import PLEC

prot_mol = next(readfile('pdb', protein_filename))
lig_mol = next(readfile('mol2', ligand_filename))
plec = PLEC(
    lig_mol, protein=prot_mol, size=1024, sparse=False)

# pickle and read back molecule
with open('lig_mol.pkl', 'wb') as f:
    pickle.dump(lig_mol, f)
with open('lig_mol.pkl', 'rb') as f:
    pkl_lig_mol = pickle.load(f)
pkl_plec = PLEC(
    pkl_lig_mol, protein=prot_mol, size=1024, sparse=False)

assert np.all(plec == pkl_plec)
>>> False
```
This is a problem when parallelizing PLEC calculations with `multiprocessing`, because you may need to pickle molecules to shuttle them between processes.

I've attached a notebook to replicate the problem.
[bug_report.zip](https://github.com/oddt/oddt/files/5343073/bug_report.zip)

**Comment by mwojcikowski** [comment]
Very interesting error, and cudos for very detailed report.

Briefly looking at the code your results may vary due to molecule loosing residue info when pickling - via SDF file for OB. The OBMol's do not pickle last time I checked. That leads to PLEC "automagically" skipping waters via RESNAME to fail. Could you confirm that differing protein-ligand pairs contain water?

I will try to investigate that issue further in the mean time.

**Comment by mwojcikowski** [comment]
That seems to be offending commit here https://github.com/oddt/oddt/commit/5d5ba842a59925df4c136da5fb48dadc5b115752
If you switch back your pickle_format to mol2 I'd expect things to be normal again.

Unfortunately there is little we could do with OB https://github.com/openbabel/openbabel/issues/272

**Comment by luponzo86** [comment]
Thanks for replying so quickly!
I don't think there's water in any of these protein-ligand pairs...
I also originally noticed this problem in another dataset, that unfortunately I cannot share, and where I am certain there is not water.

I will try your last suggestion, thanks!

**Comment by mwojcikowski** [comment]
As a side note: you should avoid passing molecules via multiprocessing in OB, since you end up writing and reading them back via some format (SDF or mol2). You should either pass string with raw file contents or the filename itself. This way the work of reading the files will also be parallelized.

**Comment by luponzo86** [comment]
> That seems to be offending commit here [5d5ba84](https://github.com/oddt/oddt/commit/5d5ba842a59925df4c136da5fb48dadc5b115752)
> If you switch back your pickle_format to mol2 I'd expect things to be normal again.

I can confirm that after reverting to `pickle_format = 'mol2'` the pickling procedure works as expected for molecules read from a `mol2` file.
Just for completeness, if the ligand molecule is read from a `.pdb` (or `.pdbqt` file, as in the notebook), the problem resurfaces, while with `pickle_format = 'sdf'` the issue was not present. I am aware that using PDB for small molecules is not optimal however :)

**Comment by luponzo86** [comment]
> As a side note: you should avoid passing molecules via multiprocessing in OB, since you end up writing and reading them back via some format (SDF or mol2). You should either pass string with raw file contents or the filename itself. This way the work of reading the files will also be parallelized.

Thanks for the suggestion! I wasn't aware of this :)

**Comment by mwojcikowski** [comment]
@luponzo86 Do you have a protein-ligand pair affected by this bug that you can share and could be used in tests?

**Comment by RJ-Li** [comment]
Sorry to bother, BUT I don't know how to solve this problem:

`sklearn.exceptions.NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this est...`

I am using 
```
import oddt
from oddt.scoring.functions.RFScore import rfscore 
rf_score = RFScore(version=2, protein=prot_mol)
```
to score ligands.
@mwojcikowski
