### ISSUE TITLE
Output ligands and protein shown not bound

### ISSUE THREAD

**Issue by parkc23** [oddt/oddt#142]
The output ligands scored by ODDT are far away from the protein employed (not bound) when I tried to check the binding mode. What has gone wrong here?
Thanks.

**Comment by mwojcikowski** [comment]
Hi @parkc23! Most probably your docking box is centered not correctly (maybe 0,0,0). You should use proper coordinates or center it using `auto_ligand`. The ligand you use for centering should be a crystal ligand most preferably.

If you could provide exact way you are trying to dock (script or command line) I can try to help you further.

**Comment by parkc23** [comment]
Your suggestion solved it. Thanks a lot!
