### ISSUE TITLE
oddt start

### ISSUE THREAD

**Issue by amorim89** [oddt/oddt#143]
Hello @mwojcikowski, I am a basic user and would like to use your tool via CLI, however I am facing some difficulties. I have created an virtualenv and installed the dependencies, but I have no idea in which dir I put the files, and I'm having trouble getting started...

thanks

<img width="960" alt="2020-11-10 (3)" src="https://user-images.githubusercontent.com/74213690/98754969-b04f0500-2395-11eb-8aa4-a4b55adb2a66.png">

**Comment by mwojcikowski** [comment]
Can you check with `conda list` if you have installed oddt in the correct environment please?

**Comment by amorim89** [comment]
Yes, oddt is in the created environment. The only package I couldn't download is sklearn-compiledtrees

**Comment by mwojcikowski** [comment]
@amorim89 compiledtrees is optional. Let me know if you still have this issue - feel free to reopen.
