### ISSUE TITLE
simple scoring example

### ISSUE THREAD

**Issue by PatWalters** [oddt/oddt#150]
Hi,

I'm trying to put together a simple scoring example.  I tried the code below, which I thought would load a model, but I get an error saying "This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.".    What am I doing wrong?  

Thanks in advance for your help. 

import oddt
oddt.toolkit = oddt.toolkits.rdk

from oddt.scoring.functions.RFScore import rfscore

for lig_mol in oddt.toolkit.readfile('sdf', '1bmk_lig.sdf'):
    break

for prot_mol in oddt.toolkit.readfile('pdb', '1bmk_prot.pdb'):
    break

rf = rfscore(protein=prot_mol)
rf.load()
rf.predict_ligand(lig_mol)

**Comment by mwojcikowski** [comment]
Hi @PatWalters 

The `load` method returns the actual trained model, but you did not assign it to any variable. Please try following code:
```python
rf = rfscore().load()
rf.set_protein(prot_mol)
rf.predict_ligand(lig_mol)

**Comment by PatWalters** [comment]
Thanks, @mwojcikowski for the incredibly quick response, and for a great package! 
In case anyone else wants to do this, here's a complete example.

import oddt
oddt.toolkit = oddt.toolkits.rdk

from oddt.scoring.functions.RFScore import rfscore

for lig_mol in oddt.toolkit.readfile('sdf', '1bmk_lig.sdf'):
    break

for prot_mol in oddt.toolkit.readfile('pdb', '1bmk_prot.pdb'):
    break

rf = rfscore().load()
rf.set_protein(prot_mol)
rf.predict_ligand(lig_mol)
print(f"score={float(lig_mol.data['rfscore_v1']):0.2f}")

**Comment by RJ-Li** [comment]
Excuse me, I tried a simple score using RFscore, but it says I need fit the estimator, which I have no idea of.
```
import oddt
from oddt.scoring.functions.RFScore import rfscore

rf = rfscore().load()
...
            rf.set_protein(prot_mol)
            score = rf.predict_ligand(lig_mol)
            formatted_score = f"{score:.2f}"
            print(f'{pdb_id}_ligand.mol2', formatted_score)
```

It raises error: sklearn.exceptions.NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

Hope you can help me @PatWalters
