### ISSUE TITLE
Where get the data "input_ligands.sdf" ?

### ISSUE THREAD

**Issue by elliotnam** [oddt/oddt#16]
Hi
I am trying to run oddt_cli  and I found you put input_ligands.sdf as argument . 
It seems like data file But I can't find where it is 
Could you point me where I get it If you don't mind thx

**Comment by mwojcikowski** [comment]
It's not an existing file, rather an example of usage of `oddt_cli`. Any input file of your choice will be fine. Pick a file you want to use in `oddt_cli` (dock, score or whatever).

If you really don't have any input files, then you can use ligands on our `experimental-pandas` branch [here](https://github.com/oddt/oddt/tree/experimental-pandas/tests/data/dude/xiap).

**Comment by elliotnam** [comment]
thanks for your kind and quick reply
One more thing, I am very interested in applying Pandas on your project and looks like you are working on it . What is your schedule on pandas. I'd like to change the codes using Pandas
If you are O.K I'll ask questions about it

**Comment by mwojcikowski** [comment]
The code is complete for now, I'm just missing documentation and some docstrings. It should be done in a week or so. If you are interested in using it as is, then install the development branch:

> pip install git+https://github.com/oddt/oddt.git@experimental-pandas

**Comment by elliotnam** [comment]
Hi
I tested three files 
I used oddt_cli using actives_docked.sdf, actives_rdkit.sdf , crystal_ligand.sdf. files 
But I got errors
the options are follow
actives_rdkit.sdf  --dock autodock_vina --receptor rec.mol2 --auto_ligand crystal_ligand.mol2 --score rfscore_v2 -O output_ligands.sdf

anthing wrong ?

**Comment by mwojcikowski** [comment]
What kind of errors? Do you have Autodock Vina installed? ODDT is looking for it in your PATH. Test it by issuing `which vina` in your terminal.

**Comment by elliotnam** [comment]
I installed pymol but din't install Vina and Can't find how to install  autodock vina 

these are errors I got 
1)
/usr/bin/python2.7 actives_rdkit.sdf --dock autodock_vina --receptor rec.mol2 --auto_ligand crystal_ligand.mol2 --score rfscore_v2 -O output_ligands.sdf /home/elliotnam/PycharmProjects/DeePOddt2/bin/oddt_cli
  File "actives_rdkit.sdf", line 2
    RDKit          3D
    ^
IndentationError: unexpected indent

2) 
/usr/bin/python2.7 crystal_ligand.sdf --dock autodock_vina --receptor rec.mol2 --auto_ligand crystal_ligand.mol2 --score rfscore_v2 -O output_ligands.sdf /home/elliotnam/PycharmProjects/DeePOddt2/bin/oddt_cli
  File "crystal_ligand.sdf", line 1
    9JZ_1_3HL5
             ^
SyntaxError: invalid syntax

3)
/usr/bin/python2.7 actives_docked.sdf --dock autodock_vina --receptor rec.mol2 --auto_ligand crystal_ligand.mol2 --score rfscore_v2 -O output_ligands.sdf /home/elliotnam/PycharmProjects/DeePOddt2/bin/oddt_cli
  File "actives_docked.sdf", line 2
    OpenBabel10071615073D
    ^
IndentationError: unexpected indent

**Comment by elliotnam** [comment]
Oh
I installed autodock-vina

**Comment by mwojcikowski** [comment]
You have to run oddt_cli which you're not doing.

> /home/elliotnam/PycharmProjects/DeePOddt2/bin/oddt_cli actives_rdkit.sdf --dock autodock_vina (..)


Fill the missing part at the end.

**Comment by elliotnam** [comment]
/usr/bin/python2.7 /home/elliotnam/PycharmProjects/OddtPandas/bin/oddt_cli actives_docked.sdf --dock autodock_vina --receptor rec.mol2 --auto_ligand crystal_ligand.mol2 --score rfscore_v2 -O output_ligands.sdf


I run this and get this error 
Traceback (most recent call last):
  File "/home/elliotnam/PycharmProjects/OddtPandas/bin/oddt_cli", line 228, in <module>
    main()
  File "/home/elliotnam/PycharmProjects/OddtPandas/bin/oddt_cli", line 161, in main
    receptor = six.next(oddt.toolkit.readfile(extension, args.receptor))
  File "/home/elliotnam/PycharmProjects/OddtPandas/oddt/toolkits/ob.py", line 95, in readfile
    return pybel.readfile(format, filename, opt=opt)
  File "/usr/lib/python2.7/dist-packages/pybel.py", line 142, in readfile
    raise IOError("No such file: '%s'" % filename)
IOError: No such file: 'rec.mol2'

where can I find rec.mol2 ?
and on the example script , You sue several data files such as

crystal_ligand_mol2 
actives_final.mol2.gz
ampc_docked.sdf

Is it possible to get these files ?
thx

**Comment by mwojcikowski** [comment]
The rec.mol2 is your protein (commonly called receptor). You have one under the link I've provided.
