### ISSUE TITLE
you have a mol2 parser in there?

### ISSUE THREAD

**Issue by UnixJunkie** [oddt/oddt#170]
I am looking for the mol2 parser you were trying to push into rdkit in the past.
I cannot find it back, but I think you were quite advanced.

**Comment by mwojcikowski** [comment]
Here you go https://github.com/mwojcikowski/rdkit/blob/60081d31f45fa8d5e8cef527589264c57dce7c65/rdkit/Chem/Mol2Writer.py

**Comment by UnixJunkie** [comment]
thanks a lot

**Comment by UnixJunkie** [comment]
at least the reader part should be integrated into rdkit; that would remove a lot of pain when dealing with mol2 files.
This is the only chemical file format I know of which is extensively used in docking; because it has 3D + partial charges.
