### ISSUE TITLE
ValueError in 

### ISSUE THREAD

**Issue by iwatobipen** [oddt/oddt#4]
Dear,
I read  the article. It's nice work.
But I couldn't run ipython notebook in supporting information.
When I run Snippet_1.ipynb, value error was occurred.
Error message is following.

   raise ValueError('Docking engine %s was not implemented in ODDT' % engine)
ValueError: Docking engine vina was not implemented in ODDT
Vina was already installed. But same error was occured.
I wonder if you have any suggestion or advice, you could provide would be greatly appreciated.

**Comment by mwojcikowski** [comment]
The correct name of docking engine is "autodock_vina". Could you point me to the place where you've found "vina"? If you replace "vina" with "autodock_vina" everything should work just fine.

**Comment by iwatobipen** [comment]
Dear mwojcikowski,
Thank you for your quick reply.
It's worked fine.
Many thanks.
