### ISSUE TITLE
atom_dict performance issues with RDKit

### ISSUE THREAD

**Issue by rlatawiec** [oddt/oddt#41]
Creating an `atom_dict` takes much longer when using rdk rather than openbabel as the backend toolkit. I think most of that time is spent on checking atom types with `_sybyl_atom_type` and calling ` _atom_matches_smarts` so many times inside of it.

Now, it's not that much of a problem for smaller molecules but with proteins some operations with rdk can become unworkably slow, especially compared to openbabel.

I feel like there are a few ways to go about it:

- Somehow make it an option not to check the atom types because sometimes it's not needed
- Rewrite the parts that don't need type checking to not use `atom_dict` 
- Display a warning when using features that require an `atom_dict`
- Not let the user use those features with rdkit, but that's probably the worst option

Thanks for looking into it.

**Comment by mwojcikowski** [comment]
The inferior performance is connected with two things: 

* molecular features are found with SMARTS matching
* mol2 atom types which also rely on repetitive SMARTS matching

We could try to improve that in the future, although it's not straightforward.
