### ISSUE TITLE
UnboundLocalError when using shape similarity from command line

### ISSUE THREAD

**Issue by samoturk** [oddt/oddt#46]
I'm trying to calculate some shape similarity from the command line using oddt:
```bash
oddt_cli db.sdf -i sdf -O result.sdf -o sdf --similarity electroshape --query q.sdf --cutoff 0.8 --toolkit rdk
```
And I get the following error:
```
Traceback (most recent call last):
  File "/home/samo/anaconda3/bin/oddt_cli", line 257, in <module>
    main()
  File "/home/samo/anaconda3/bin/oddt_cli", line 191, in main
    pipeline.similarity(sim, query, protein=receptor, cutoff=args.cutoff)
UnboundLocalError: local variable 'receptor' referenced before assignment

```
When I remove " protein=receptor" to go around this issue, I get 'NameError', because you forgot to import `usr_similarity` in `oddt.virtualrscreening` (line 18). Fixing the import fixes this problem.

Package was installed using pip and I'm using anaconda python distribution (python 3.6).

**Comment by mwojcikowski** [comment]
The issue is fixed in git master. You can install it via `pip install git+https://github.com/oddt/oddt.git`
