### ISSUE TITLE
Index error in min_symmetry RMSD method

### ISSUE THREAD

**Issue by ravila4** [oddt/oddt#67]
The min_symmetry method gives an index error for some molecules when subsetting the ref_atoms matrix using `ref_atoms[match]` after the hydrogen atoms have been removed.

A suggested fix is to change:
`ref_atoms = ref.coords[ref.atom_dict['atomicnum'] != 1]`
to: 
`ref_atoms = ref.coords`

**Comment by mwojcikowski** [comment]
I'm assuming you are using RDKit backed, right? I've opened a PR #68 to fix this issue. Could you provide some of the failing molecules to verify if the fix works?

**Comment by ravila4** [comment]
I have both toolkits installed. The error happens for any molecule where the hydrogens are mixed-in with the heavy atoms, i.e. not located at the bottom of the file. The molecules in file below are all taken from the jcheminf notebook repository.

[ampc_failed_compounds.zip](https://github.com/oddt/oddt/files/1669112/ampc_failed_compounds.zip)

**Comment by mwojcikowski** [comment]
I think I've fixed the bug you have reported in #68 You can try it yourself by installing this branch via pip:

> pip install git+https://github.com/oddt/oddt.git@fix-rmsd

The fix should hit next release of ODDT which I plan to do some time in February.

**Comment by mwojcikowski** [comment]
We believe that this issue is fixed now with #68 and will close for now. If you have further problems with `rmsd` please feel free to reopen.

**Comment by ravila4** [comment]
Thank you, I just had an opportunity to test with several molecule sets, and it seems to work well.
