### ISSUE TITLE
Snippet 1 not producing csv files

### ISSUE THREAD

**Issue by dcastaneda5** [oddt/oddt#70]
Hi!
I was taking a look at snippet 1, and I had the same problem with the hydrogen bonds as it was mentioned in issue #67 . After that I installed the pip install git+https://github.com/oddt/oddt.git@fix-rmsd that was suggested to fix the bug, however, after running snippet #1, it produces a pdbqt file, but not a .csv with the scores.

**Comment by mwojcikowski** [comment]
I've just tried it and it worked for me. Could you please some additional information about your setup (which toolkit, toolkit version, python version)?

Currently when you write to a file, say mol2, at the end it's plugged again to the pipeline. If you use old OpenBabel (<=2.3.2) then mol2 does not support additional attributes to be stored with a molecule. Try sdf then and report back.

We are working on an efficient solution to store molecules differently if user wishes to store molecules for further use.

**Comment by mwojcikowski** [comment]
I just re-read your question and realized you've used pdbqt as an output format, so currently it will destroy your molecular data. You should use the `csv_filename` param in `virtualscreening.write` method to save CSV along with molecules.

**Comment by dcastaneda5** [comment]
Sorry I just read this! I see, I'll try again by using the suggested changes! Thanks a lot!
