### ISSUE TITLE
Do not renumber residue id in protein input file 

### ISSUE THREAD

**Issue by fabricecarles** [oddt/oddt#71]
Hi Maciej very good tool, thanks,

I try to extract the list of residues that interact with a ligand using oddt 

I separate protein and ligand from PDB in two respective files. Then I try to access the residues involved in hbond. 
Unfortunately by default residues numbering in oddt do not respect the input file uniprot numbering and provide a new residues numbering starting at res1. 
How can I force oddt to keep the original numbering (including gap) ?

Fabrice

PhD student Orleans University, France

**Comment by marta-sd** [comment]
Hi Fabrice,

You're using Open Babel as a backend, right?

The `idx` attribute corresponds to the index used in OB, not to the residue number. However, the original residue numbering isn't lost and you can access it using `res.OBResidue.GetNum()` (where `res` is a residue object).

@mwojcikowski Is that intended? I think we should change it (RDKit uses residue number as `idx`)

**Comment by fabricecarles** [comment]
Hi Marta,
I was using OB backend but in fact I don't know why ! When we use oddt.toolkit.readfile,  OB is the default backend ? 
Now I have switched the readfile to oddt.toolkits.rdk.readfile and RDKit seem to be the new backend with residue number as idx. This is exactetly what I want, perfect !  
Thanks

**Comment by marta-sd** [comment]
If you have both RDKit and Open Babel installed, the latter is used by default.
You can change this behavior by setting `ODDT_TOOLKIT` env variable to `rdkit`, or by putting `oddt.toolkit = oddt.toolkits.rdkit` inside your script.

**Comment by fabricecarles** [comment]
Thanks again !  Note that the exact module name is rdk ( `oddt.toolkit = oddt.toolkits.rdk` )

**Comment by mwojcikowski** [comment]
Sure, I think we should change the indexing in OB, although the `idx` property is taken from OpenBabel's `GetIdx` vs `GetNum`. Maybe we should make a distinction between them and create `Residue.number` property and fix `Residue.idx` as an 0-based index for RDKit.

**Comment by marta-sd** [comment]
Sounds reasonable

**Comment by fabricecarles** [comment]
Hi, 
In version 0.5 of oddt I was using 
`oddt.toolkit = oddt.toolkits.rdk  #  force rdkit backend`
By default oddt was not renumbering residue id in protein input file.
Since version oddt 0.6 with same rdkit backend the default behavior is now to renumbering.

How can I force oddt 0.6 (rdkit) to keep again the original numbering (including gap) ?

Could you provide some code example

Tanks

**Comment by mwojcikowski** [comment]
ODDT 0.6 introduced residue `number` property which maps to PDB numbering. `idx` which was previously that number is used as an consecutive index to match that of OpenBabel. So if I understand correctly all you need to do is to use `Residue.number` instead of `Residue.idx` (see the [docs](https://oddt.readthedocs.io/en/latest/rst/oddt.toolkits.html#oddt.toolkits.rdk.Residue)). If you have further problems please open new issue with a bit of code showing the changed behavior.

**Comment by mwojcikowski** [comment]
Here is a bit of code that prints PDB numbering with 

```python
import oddt
oddt.toolkit = oddt.toolkits.rdk #  force rdkit backend
mol = next(oddt.toolkit.readfile('pdb', 'tests/data/dude/xiap/receptor_rdkit.pdb'))
for res in mol.residues:
    print(res.number)
```

If you want to use `atom_dict` you need to mark a molecule as a protein:

```python
import oddt
oddt.toolkit = oddt.toolkits.rdk #  force rdkit backend
mol = next(oddt.toolkit.readfile('pdb', 'tests/data/dude/xiap/receptor_rdkit.pdb'))
mol.protein = True
print(mol.atom_dict['resnum'])
```
