### ISSUE TITLE
Support for internal parallelization in Vina

### ISSUE THREAD

**Issue by ravila4** [oddt/oddt#75]
Currently, the `n_cpu` parameter in the virtual screening pipeline allows for running several Vina processes concurrently. However, Vina also has support for internal parallelization when run through the commandline with the `--cpu` argument. Is it possible to implement both types of parallelization in the pipeline?

**Comment by marta-sd** [comment]
Yes, it is possible, and there are two ways to achieve this. (I just realized the arguments you need to use aren't documented, sorry for that!)

First, when you use `dock` or `score` method you can pass some additional arguments to Autodock Vina. It can be e.g. `n_cpu` argument, which is exactly what you need. Here's an example:
```python
from oddt.virtualscreening import virtualscreening

dude_data_dir = 'tests/data/dude/xiap/'
xiap_crystal_ligand = dude_data_dir + 'crystal_ligand.sdf'
xiap_protein = dude_data_dir + 'receptor_rdkit.pdb'

vs = virtualscreening(n_cpu=1)
vs.load_ligands('sdf', xiap_crystal_ligand)
vs.dock(engine='autodock_vina',
        protein=xiap_protein,
        auto_ligand=xiap_crystal_ligand,
        n_cpu=4)
mols = list(vs.fetch())
```

Secondly, the automatic switching to Internal parallelization has been implemented recently (#66). It works as follows: if a number of molecules processed at once (controlled by `chunksize`) is smaller than the number of CPUs, `n_cpu` argument from `virtualscreening` object is automatically passed to functions in the pipeline (so to Autodock Vina, if you use it). Here's a piece of code responsible for that:
https://github.com/oddt/oddt/blob/3e9460a741e05a9948887ec2b11b9a7894dccb39/oddt/virtualscreening.py#L336-L352

**Comment by mwojcikowski** [comment]
On top of what @marta-sd said you can do nested parallelization, so by setting 2 cpus in VS and 2 for Vina you get total off 2*2=4 cpus utilized.

```python
vs = virtualscreening(n_cpu=2)
vs.load_ligands('sdf', xiap_crystal_ligand)
vs.dock(engine='autodock_vina',
        protein=xiap_protein,
        auto_ligand=xiap_crystal_ligand,
        n_cpu=2)
mols = list(vs.fetch())
```

**Comment by ravila4** [comment]
Thanks, this is very helpful!
