### ISSUE TITLE
Charges in PDBQT files

### ISSUE THREAD

**Issue by dcastaneda5** [oddt/oddt#77]
Hi! I tried using the following code to convert a pdb file to pdbqt:

`# Script for converting receptors to pdbqt using ODDT

import sys
import oddt
from oddt.docking.AutodockVina import write_vina_pdbqt

if len(sys.argv) != 4:
	    print("Usage:", sys.argv[0], "<format> <receptor> <output_folder>")

else:
	file_type = sys.argv[1]
	receptor_file = sys.argv[2]
	path = sys.argv[3]

	# Read input molecule
	receptor = next(oddt.toolkit.readfile(file_type, receptor_file))
										    
	# Write output 
	write_vina_pdbqt(receptor, path, flexible=False)
`

However, after running it, the new generated pdbqt file gives something like this:

REMARK  Name = /home/dcastaneda5/refined-set/proteins/966c/966c_protein.pdb
REMARK                            x       y       z     vdW  Elec       q    Type
REMARK                         _______ _______ _______ _____ _____    ______ ____
ATOM      1  N   ARG A 108      23.316   4.711  38.249  0.00  0.00    +0.000 N 
ATOM      2  HN1 ARG A 108      23.239   3.947  38.950  0.00  0.00    +0.000 HD
ATOM      3  HN2 ARG A 108      23.093   4.340  37.304  0.00  0.00    +0.000 HD
ATOM      4  HN3 ARG A 108      24.284   5.091  38.254  0.00  0.00    +0.000 HD
ATOM      5  CA  ARG A 108      22.352   5.803  38.595  0.00  0.00    +0.000 C 
ATOM      6  HA  ARG A 108      21.366   5.352  38.479  0.00  0.00    +0.000 HD
ATOM      7  C   ARG A 108      22.351   7.000  37.650  0.00  0.00    +0.000 C 
ATOM      8  O   ARG A 108      23.334   7.246  36.900  0.00  0.00    +0.000 OA
ATOM      9  CB  ARG A 108      22.566   6.266  40.036  0.00  0.00    +0.000 C 
ATOM     10  HB1 ARG A 108      21.876   7.087  40.232  0.00  0.00    +0.000 HD
ATOM     11  HB2 ARG A 108      22.332   5.431  40.696  0.00  0.00    +0.000 HD
ATOM     12  CG  ARG A 108      23.953   6.738  40.359  0.00  0.00    +0.000 C 

As you can see, I get a bunch of zeroes, and its repeated along every atom of my pdbqt file. The reason why I tried using this code in the first place, is because I initially converted pdb to pdbqt using "prepare_protein4.py" code (which is part of MGL tools), and I found out that I was getting zeroes as well with metallic ions, so I decided to give it a shot with oddt. 

Thanks in advance!

**Comment by mwojcikowski** [comment]
The remarks partially answer your question, those three columns are:
* vdW (van der Waals radii)
* Elec (electrostatic potential)
* q (partial charge)
You will get partial charge should you generate it beforehand.

Anyhow, Autodock *Vina* does not use any of those columns. Autodock 4 will use the partial charges, I don't think the vdW and Elec is necessary at all (unless you want to override the default values).

**Comment by dcastaneda5** [comment]
Thank you for your fast response. However, could you tell me how to generate these partial charges that you mention beforehand? I was under the impression that this code would generate them for me.
We are using a modified version of NNScore and we are testing different pdbqt files for it. We initially generated pdbqt files using MGLtools ("prepare_protein4.py"), but we noticed that it does not calculate charges for metallic ions in the files. To my knowledge NNScore uses partial charges for scoring.

Thanks in advance.

**Comment by mwojcikowski** [comment]
Yes, in fact NNscore uses partial charges in computing Coulombic interactions. You can generate partial charges with `mol.calccharges()` ant they should appear in the PDBQT file. Note, that RDKit does not have this functionality yet. PR is coming soon.

**Comment by mwojcikowski** [comment]
Finally, you could use NNscore which is implemented in ODDT: 
```python
from oddt.scoring.functions import nnscore
```
According to our tests it performs better than the original one on either PDBbind and DUD-e database. Additionally it is much faster and does not require PDBQT files.

**Comment by mwojcikowski** [comment]
When you read molecule from PDB usually you get zero order bonds coordinating the metal atoms, to which OB is apparently not invariant. I've checked for `xiap` and following code fixes charge generation

```python
import oddt
mol = next(oddt.toolkit.readfile('pdb', 'xiap_receptor.pdb')
# remove zero order bonds from metals
for atom in mol: 
    if atom.atomicnum == 30:  # Atomic num of treated metals
        for bond in atom.bonds:
            mol.OBMol.DeleteBond(bond.OBBond)

mol.calccharges()
```

For other atoms change the if to a list of atomic numbers of metals.

**Comment by ravila4** [comment]
Hi, I tried the suggested method for calculating charges with `xiap`, but it didn't work. The bonds were removed, but it still throws the same error as before. Could there be a difference across openbabel versions? I am using 2.4.1.

Also, I tried using the RDKit backend, but it fails with `TypeError: category must be a Warning subclass, not 'str'`. I think [#79](https://github.com/oddt/oddt/pull/79) fixes that.

**Comment by marta-sd** [comment]
You're right, this example doesn't work with OB 2.4.1 and the default model, we'll take a look at that. Meanwhile you can use different model, e.g. MMFF94 works for this one: `mol.calccharges('mmff94')`.

*Disclaimer: charging molecules in OB is painful, it is often impossible to find a pipeline that works for all compounds in the database...*

And with RDKit you're right again, there was an error in the warning, thank you for fixing it (and welcome to the ODDT team :)) Note, however, that it means that RDKit wasn't able to calculate the charges properly (there are some NaNs etc)

**Comment by mwojcikowski** [comment]
Before our PR #78 the default method for `mol.calcchrges` was `mmff94`, which works for `xiap`. On the other hand `gasteiger` partial charges are suggested for small molecules, thus we unified that for OB and RDKit by setting default method to `gasteiger` (the most common use case is small molecule). On the other hand 'mmff94' should work better for proteins and, as pointed out by @marta-sd, they work for `xiap` so i suggest using it. Gasteiger for proteins is problematic most times.

**Comment by mwojcikowski** [comment]
I think this discussion drifted apart from the original issue, so I'm going to close this. Open a new issue, should you have other problems.
