### ISSUE TITLE
SimpleInteractionFingerprint error

### ISSUE THREAD

**Issue by Marcosuff** [oddt/oddt#80]
Hello,
I'm using ODDT to generate SILIRID fingerprints and came across an error. It works most of the times, but for some poses of a docked molecule I get an error using this code:

`from oddt.fingerprints import SimpleInteractionFingerprint`

`ligand = list(oddt.toolkit.readfile('mol2', '2c8z_clean/2vth_ligand.mol2'))`
`rec = next(oddt.toolkit.readfile('mol2','_proteins_/2c8z_clean.mol2'))`
`rec.protein=True`

`for m in ligand:`

    ifp = SimpleInteractionFingerprint(m,rec)

    print(ifp)`

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/marcos/anaconda3/lib/python3.6/site-packages/oddt-0.4.1-py3.6.egg/oddt/fingerprints.py", line 176, in SimpleInteractionFingerprint
    amino_acids, acceptors[strict1]['resname']), 4], 1)
IndexError: index 21 is out of bounds for axis 0 with size 21

Any idea what's causing this problem? As you can see, it generates fingerprints for some poses of the ligand but fails on the last one.

**Comment by Marcosuff** [comment]
[protein_ligand.zip](https://github.com/oddt/oddt/files/1858273/protein_ligand.zip)
These are the files I used.

**Comment by mwojcikowski** [comment]
Hello @Marcosuff,

Thank you for reporting an issue. It appears that you've hit a bug which was fixed in the last release of ODDT (`0.6`) and you are using `0.4.1`. Please upgrade to the latest version with:
> conda install -c oddt oddt

I tested the files you've reported and there is no such error, although the protein is not the one you docked the ligands to, thus all 0s in final fingerprint.

If you have already computed some Simple IFPs you'd have to recalculate them since the order of amino acids had changed and you cannot compare them to each other.
