### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Marcosuff** [oddt/oddt#81]
Hello,
I ran into an issue while reading a pdb file with ODDT. 
This is the part that caused the problem:

`rec = next(oddt.toolkit.readfile('pdb','PDBBind2017_proteins/1px4_protein.pdb'))`

Reading protein 1px4.pdb (from PDBBind2017 refined set) I always get an error. 

These are my system specs:
Arquitetura:           x86_64
Modo(s) operacional da CPU:32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per núcleo  2
Núcleo(s) por soquete:4
Soquete(s):            1
Nó(s) de NUMA:        1
ID de fornecedor:      GenuineIntel
Família da CPU:       6
Modelo:                60
Model name:            Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz
Step:                  3
CPU MHz:               3326.250
CPU max MHz:           4000,0000
CPU min MHz:           800,0000
BogoMIPS:              6385.79
Virtualização:       VT-x
cache de L1d:          32K
cache de L1i:          32K
cache de L2:           256K
cache de L3:           8192K
NUMA node0 CPU(s):     0-7

**Comment by mwojcikowski** [comment]
This is Open Babel problem and, I'm sorry to say, we can do little with it. You could try to convert the segfaulting proteins to mol2 or other supported format, maybe it will be successful.

In the recent ODDT there is a warning for a list of protein files that segfault (see [code](https://github.com/oddt/oddt/blob/a7b3b6128b2a9c9203fdbb2c0e0025500ecf7ec0/oddt/datasets.py#L40) when using `oddt.dataset.pdbbind` object. Note `1px4` is one of them with additional note that it fails on systems with little RAM. I didn't have issues with those on a server with 128GB of RAM, but I'm not sure what is the exact requested amount.
