### ISSUE TITLE
Docking engine %s was not implemented in ODDT

### ISSUE THREAD

**Issue by aminemosbah** [oddt/oddt#92]
tried to run the Snippet_1 tutorial and got stuck with this error 
C:\Windows\System32\oddt\oddt\virtualscreening.py in dock(self, engine, protein, *args, **kwargs)
    246         if engine.lower() == 'autodock_vina':
    247             from oddt.docking import autodock_vina
--> 248             engine = autodock_vina(protein, *args, **kwargs)
    249         else:
    250             raise ValueError('Docking engine %s was not implemented in ODDT

**Comment by mwojcikowski** [comment]
Automated discovery of Vina binary is flawed on Windows, I will try to find a better way of doing it.

In the meantime you can use `executable` argument of of dock/autodock_vina to point it to a vina binary:
```python
pipeline.dock('autodock_vina', 'ampc/receptor.pdbqt', 'ampc/crystal_ligand.mol2', executable='path/to/vina.exe')
```

PS.
Sorry that I missed #90

**Comment by aminemosbah** [comment]
great thanks for you help
however the next line of code got crushed and here it is

   1 # Write docked ligands conformations to a file (including scores)
----> 2 pipeline.write('mol2', 'ampc_docked.mol2', overwrite=True, opt={'c':None})

D:\Anaconda3\envs\drugdesign\lib\site-packages\oddt\virtualscreening.py in write(self, fmt, filename, csv_filename, **kwargs)
    403                                                   filename,
    404                                                   overwrite=True,
--> 405                                                   **kwargs)
    406         if csv_filename:
    407             f = open(csv_filename, 'w')

TypeError: type object got multiple values for keyword argument 'overwrite'


please help me out 
thanks

**Comment by mwojcikowski** [comment]
Just remove `overwrite=True`, it was removed and is a default now.

**Comment by aminemosbah** [comment]
Hi, sorry for the inconvenience but
One more issue
At the same line I get
Userwarning the chunksize (100) seams to be to large. Self.chunsize

Traceback 
Errno2 le chemin d access est introuvable:'/tmp//autodock-vina-yfo3z7ya'


Very grateful and sorry one more time
I m just obsessed with your pecular job

**Comment by mwojcikowski** [comment]
I will try to reproduce the error on my Windows machine, although it seam that you are still missing Autodock Vina. How did you installed ODDT and other dependencies?

**Comment by aminemosbah** [comment]
hi, 
for the installation, I flowed through on the steps of the readme file  and all seemed to be ok  (i presume so!)
for the autodock vina ; i pointed to the executable path just as you have already suggested and i run the command without any warnings thank you for helping out, a really need your package for my paper. 
thanks

**Comment by mwojcikowski** [comment]
I managed to reproduce that error, and some of the variables have default values that do not work smooth on Windows - this needs to be fixed. In the meantime you have to submit a temporary path for vina files with `prefix_dir` argument (default is `/tmp` which obviously is not there on windows).

I run the notebook by changinfg the dock line to:
```python
# Dock entire library to receptor, autocenter docking box on  ligand
pipeline.dock('autodock_vina', 'ampc/receptor.pdbqt', 'ampc/crystal_ligand.mol2', 
              executable='C:\Users\maciek\Miniconda3\envs\py27\\bin\Windows-vina.exe', prefix_dir='.')
```
The `.` means that the temp files are going to be placed next to the notebook itself.

**Comment by aminemosbah** [comment]
hi, trying to run the code , very slow and get stuck  with this message 

":\Anaconda3\envs\drugdesign\lib\site-packages\oddt\virtualscreening.py:345: UserWarning: The chunksize (100) seams to be to large.
  % self.chunksize)"

even if i downsized the chunksize=30, 
the only result i got until now is the creation of 'autodock_vina_d04d1aal' file in the notebook directory what to do, keep it running or shut it down?
regardes

**Comment by mwojcikowski** [comment]
Two additional things:
- training NNscore takes ~1h, so you might want to disable (hash) nnscore rescoring;
- I have noticed an OpenBabel bug that surfaces in Windows, I'm preparing a fix for that issue.

**Comment by aminemosbah** [comment]
i m still at the previous step 
# Write docked ligands conformations to a file (including scores)
pipeline.write('mol2', 'ampc_docked.mol2', opt={'c':None})

and the code is blocked ???
how did you manage to pass over to  the next line of code ?

**Comment by mwojcikowski** [comment]
If it is blocked it probably is docking. Check your task manager. Invoking `vs.write(...)` actually triggers the computations. Until then they are lazy and are queued until write or fetch is called.

**Comment by aminemosbah** [comment]
yes your right there is an issue with openbabel

*** Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Cannot initialize database 'types.txt' which may cause further errors.
[I 10:01:25.458 NotebookApp] Saving file at /Snippet_1.ipynb
[I 10:03:24.927 NotebookApp] Saving file at /Snippet_1.ipynb

**Comment by aminemosbah** [comment]
actually, openbabel is complicated to set up on google collab which humper seriously the possibility to run ODDT on the cloud,???!!!
 i will very grateful if you could screw this away 
1000 thanks

**Comment by mwojcikowski** [comment]
I need to retest it on Windows, but #93 should take care of those you had. I plan to add Appveyor Windows testing to CI for the future.

**Comment by aminemosbah** [comment]
hi, 
still getting the same error even after the amendments (93)
*** Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Cannot initialize database 'types.txt' which may cause further errors.
hope the windows appveyr is coming soon

**Comment by mwojcikowski** [comment]
I managed to identify the problem - the logp was failing, and all molecules were filtered out. You have to hash the logp filter in the pipeline and the docking will be done.

```python
# pipeline.apply_filter('0 < mol.logp < 5')
```

**Comment by aminemosbah** [comment]
I will try it out and get back to you,
I need your mail I m holding a data science event a need to discuss it with you
Thanks

**Comment by aminemosbah** [comment]
hi
the same issue with open babel even with hashing the logp filter 

*** Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Cannot initialize database 'types.txt' which may cause further errors.

do i need to reset the #93 amendments

**Comment by aminemosbah** [comment]
hi any news

**Comment by mwojcikowski** [comment]
@aminemosbah Have you tried the latest OpenBabel from `conda-forge`?
