### ISSUE TITLE
Add the QuickVina docking engine

### ISSUE THREAD

**Issue by diallobakary4** [oddt/oddt#94]
Hello 

Adding the [QuickVina ](https://github.com/QVina/qvina)docking engine will be nice. It is already working by simply setting the path for the executable.

```
from oddt.virtualscreening import virtualscreening as vs
pipeline=vs(n_cpu=8)
pipeline.dock('autodock_vina', receptor, ligands, executable="/home/user/bin/qvina/bin/qvina-w") 
```

**Comment by mwojcikowski** [comment]
Since there is really nothing we need to do on the coding side, I will add the list of compatible binaries to docs.

**Comment by mwojcikowski** [comment]
Added appropriate info to the docstrings
