### ISSUE TITLE
datasets.py does not correctly locate pdbbind index files for version greater than 2016

### ISSUE THREAD

**Issue by FBoyles** [oddt/oddt#95]
Very minor issue - PDBbind releases post-2016 store index files in the /index subdirectory. Currently, the pdbbind class from oddt.datasets only looks in {home}/index if version==2016 and otherwise defaults to looking in {home}, causing it to be unable to locate index files for the 2017 and 2018. 

Changing line 64 of datasets.py from 
`elif version == 2016`
to
`elif version >= 2016`
resolves the issue. 

I've tweaked this in my local install, but would be great to have support for the most recent PDBbind release in the release version.

**Comment by mwojcikowski** [comment]
This is explicitly set to 2016, as the indexing may change over time. We have to specify which version are supported one by one and make similar explicit statements.

This update is already planned as a part of student's project in the nearest future. We will try to push it ASAP to git's master.
