### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by ValeryPolyakov** [oddt/oddt#99]
Here is the screenshot. Up to that loop, everything else was executed successfully.

I am using Python 3.

Build training and testing descriptors
def gen_descriptors(pdbid):
    ligand = toolkit.readfile('sdf', 'v2007/%s/%s_ligand.sdf' %(pdbid, pdbid)).next()
    protein = toolkit.readfile('pdb', 'v2007/%s/%s_pocket.pdb' %(pdbid, pdbid)).next()
    return descriptor_generator.build([ligand], protein)
​
descriptors_train = np.vstack([gen_descriptors(pdbid) for pdbid in pdbbind_act_train.keys()])
descriptors_test = np.vstack([gen_descriptors(pdbid) for pdbid in pdbbind_act_test.keys()])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-513829d18228> in <module>
      4     return descriptor_generator.build([ligand], protein)
      5 
----> 6 descriptors_train = np.vstack([gen_descriptors(pdbid) for pdbid in pdbbind_act_train.keys()])
      7 descriptors_test = np.vstack([gen_descriptors(pdbid) for pdbid in pdbbind_act_test.keys()])

<ipython-input-5-513829d18228> in <listcomp>(.0)
      4     return descriptor_generator.build([ligand], protein)
      5 
----> 6 descriptors_train = np.vstack([gen_descriptors(pdbid) for pdbid in pdbbind_act_train.keys()])
      7 descriptors_test = np.vstack([gen_descriptors(pdbid) for pdbid in pdbbind_act_test.keys()])

<ipython-input-5-513829d18228> in gen_descriptors(pdbid)
      1 def gen_descriptors(pdbid):
----> 2     ligand = toolkit.readfile('sdf', 'v2007/%s/%s_ligand.sdf' %(pdbid, pdbid)).next()
      3     protein = toolkit.readfile('pdb', 'v2007/%s/%s_pocket.pdb' %(pdbid, pdbid)).next()
      4     return descriptor_generator.build([ligand], protein)
      5 

AttributeError: 'generator' object has no attribute 'next'

**Comment by mwojcikowski** [comment]
Hi Valery,

In Python 3.x you dont have next method on generators, you should use next
function instead. Just replace `toolkit.readfile(...).next()` with
`next(toolkit.readfile(...))` and you will be good to go.

If you wish to retain backward compatibility add an import from six: `from
six import next`
----
Pozdrawiam,  |  Best regards,
Maciek Wójcikowski
maciek@wojcikowski.pl


śr., 3 lip 2019 o 22:44 ValeryPolyakov <notifications@github.com>
napisał(a):

**Comment by ValeryPolyakov** [comment]
Hi Maciek,

Thanks for the suggestion, now I ran into the next issue:

def gen_descriptors(pdbid):
    ligand = next(toolkit.readfile('sdf', 'v2007/%s/%s_ligand.sdf' %(pdbid,
pdbid)))
    protein = next(toolkit.readfile('pdb', 'v2007/%s/%s_pocket.pdb'
%(pdbid, pdbid)))
    return descriptor_generator.build([ligand], protein)

descriptors_train = np.vstack([gen_descriptors(pdbid) for pdbid in
pdbbind_act_train.keys()])
descriptors_test = np.vstack([gen_descriptors(pdbid) for pdbid in
pdbbind_act_test.keys()])

---------------------------------------------------------------------------AttributeError
                           Traceback (most recent call
last)<ipython-input-7-b8d528eb1b19> in <module>      4     return
descriptor_generator.build([ligand], protein)      5 ----> 6
descriptors_train = np.vstack([gen_descriptors(pdbid) for pdbid in
pdbbind_act_train.keys()])      7 descriptors_test =
np.vstack([gen_descriptors(pdbid) for pdbid in
pdbbind_act_test.keys()])
<ipython-input-7-b8d528eb1b19> in <listcomp>(.0)      4     return
descriptor_generator.build([ligand], protein)      5 ----> 6
descriptors_train = np.vstack([gen_descriptors(pdbid) for pdbid in
pdbbind_act_train.keys()])      7 descriptors_test =
np.vstack([gen_descriptors(pdbid) for pdbid in
pdbbind_act_test.keys()])
<ipython-input-7-b8d528eb1b19> in gen_descriptors(pdbid)      2
ligand = next(toolkit.readfile('sdf', 'v2007/%s/%s_ligand.sdf'
%(pdbid, pdbid)))      3     protein = next(toolkit.readfile('pdb',
'v2007/%s/%s_pocket.pdb' %(pdbid, pdbid)))----> 4     return
descriptor_generator.build([ligand], protein)      5       6
descriptors_train = np.vstack([gen_descriptors(pdbid) for pdbid in
pdbbind_act_train.keys()])
~\AppData\Local\Continuum\anaconda3\envs\my-rdkit-env\lib\site-packages\oddt\scoring\descriptors\__init__.py
in build(self, ligands, protein)    166         out = []    167
 for mol in ligands:--> 168             mol_dict =
atoms_by_type(mol.atom_dict, self.ligand_types, self.mode)    169
       if self.aligned_pairs:    170                 pairs =
zip(self.ligand_types, self.protein_types)
AttributeError: 'NoneType' object has no attribute 'atom_dict'

Valery R. Polyakov
